import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ReduxProvider } from "@/store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="relative">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
